### ISSUE TITLE
Script encoding problem

### ISSUE THREAD

**Issue by Termainl** [NotoChen/JavaVersionChoice#1]
- I hope you adjust the script format to Windows (CR LF), currently it is Unix (LF)
- The default encoding format of windows command line CMD is gbk encoding format (codepage encoding table number: cp936). However, in some cases gbk decoding will produce garbled characters, it is recommended to add (chcp 936) to the file header to specify the encoding format of the current encoding page

**Comment by NotoChen** [comment]
![image](https://github.com/NotoChen/JavaVersionChoice/assets/46807914/7070fefd-9a01-4bb0-adc9-bffe06556cea)

currently is is Windows (CR LF)

**Comment by NotoChen** [comment]
chcp 936 >nul 
I have submitted the relevant adjustments
